# Generated by Django 3.1.3 on 2020-11-30 12:11

import asgard_mvc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image_profile', models.FileField(upload_to=asgard_mvc.models.user_directory_path)),
            ],
        ),
    ]
