# Generated by Django 3.1.3 on 2020-11-30 14:48

import asgard_mvc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='image_profile',
            field=models.ImageField(upload_to=asgard_mvc.models.user_directory_path, validators=[asgard_mvc.models.validate_file_extension]),
        ),
    ]
