# Generated by Django 3.1.3 on 2020-12-01 01:26

import asgard_mvc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0002_auto_20201130_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_xls', models.FileField(upload_to='quiz/', validators=[asgard_mvc.models.validate_quiz_file])),
            ],
        ),
    ]
