# Generated by Django 3.1.3 on 2020-12-01 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0003_quizmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
