# Generated by Django 3.1.3 on 2020-12-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0004_quizmodel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
