# Generated by Django 3.1.3 on 2020-12-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0005_auto_20201201_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('nomor', models.IntegerField(default=1)),
                ('soal', models.TextField()),
                ('jawaban_a', models.TextField()),
                ('jawaban_b', models.TextField()),
                ('jawaban_c', models.TextField()),
                ('jawaban_d', models.TextField()),
                ('poin', models.IntegerField(default=1)),
            ],
        ),
    ]
