# Generated by Django 3.1.3 on 2020-12-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0006_quizentrymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizentrymodel',
            name='poin',
            field=models.TextField(),
        ),
    ]
