# Generated by Django 3.1.3 on 2020-12-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0007_auto_20201201_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
