# Generated by Django 3.1.2 on 2020-12-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0002_auto_20201130_1434'),
        ('asgard_mvc', '0008_userprofilemodel_current_level'),
    ]

    operations = [
    ]
