# Generated by Django 3.1.3 on 2020-12-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0010_armodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='armodel',
            name='marker_pattern_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
