# Generated by Django 3.1.3 on 2020-12-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0011_armodel_marker_pattern_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armodel',
            name='marker_pattern_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='armodel',
            name='model_url',
            field=models.URLField(max_length=100),
        ),
    ]
