# Generated by Django 3.1.3 on 2020-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0012_auto_20201202_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='armodel',
            name='model_id',
            field=models.CharField(default='cat', max_length=100),
        ),
    ]
