# Generated by Django 3.1.3 on 2020-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0013_armodel_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='armodel',
            name='model_scale_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='armodel',
            name='model_scale_y',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='armodel',
            name='model_scale_z',
            field=models.IntegerField(default=1),
        ),
    ]
