# Generated by Django 3.1.3 on 2020-12-07 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0017_auto_20201202_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2020, 12, 7, 7, 26, 49, 613548))),
            ],
        ),
        migrations.AlterField(
            model_name='armodel',
            name='model_id',
            field=models.CharField(max_length=100),
        ),
    ]
