# Generated by Django 3.1.3 on 2020-12-07 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0018_auto_20201207_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 7, 27, 56, 151570, tzinfo=utc)),
        ),
    ]
