# Generated by Django 3.1.3 on 2020-12-07 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0019_auto_20201207_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 7, 34, 2, 74119, tzinfo=utc)),
        ),
    ]
