# Generated by Django 3.1.3 on 2020-12-07 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0020_auto_20201207_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 7, 38, 23, 308406, tzinfo=utc)),
        ),
    ]
