# Generated by Django 3.1.3 on 2020-12-07 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0021_auto_20201207_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='channel_name',
            field=models.CharField(default='pertemuan', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='chat_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channelmodel',
            name='channel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='channel_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 7, 50, 29, 884502, tzinfo=utc)),
        ),
    ]
