# Generated by Django 3.1.3 on 2020-12-07 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0022_auto_20201207_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='channel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='chat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 7, 50, 46, 453752, tzinfo=utc)),
        ),
    ]
