# Generated by Django 3.1.3 on 2020-12-07 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0023_auto_20201207_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 8, 20, 41, 536809, tzinfo=utc)),
        ),
    ]
