# Generated by Django 3.1.3 on 2020-12-07 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgard_mvc', '0024_auto_20201207_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelModel',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='channel_id',
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 11, 55, 7, 844314, tzinfo=utc)),
        ),
    ]
